// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eupigofafgtokxbsafff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cGlnb2ZhZmd0b2t4YnNhZmZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODY1MzcsImV4cCI6MjA2NDM2MjUzN30.vlZTT30qhMGIUBqIaEThHWm7yTtBiheA3oXHHOwvcME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);